"""
Standalone visualization script for the Photon Geodesic Integrator.

This script reads the binary blueprints generated by the C executable to render the final lensed image.
It maps the physical photon trajectories onto a static background texture and an accretion disk geometry, utilizing r_min and r_max to define the source bounds.
The rendering process executes on the host CPU, translating the geodesic data into pixels.

Author: Dalton J. Moone.
"""

import argparse
import os
import sys

import numpy as np

try:
    from nrpy.examples.geodesic_visualizations import config_and_types as cfg
    from nrpy.examples.geodesic_visualizations import render_lensed_image as rli
except ImportError as e:
    # A failure here indicates the Python path lacks the core NRPy infrastructure.
    print(f"FATAL: Failed to import NRPy visualization scripts. Error: {e}")
    sys.exit(1)


def main() -> None:
    """Parse parameters and orchestrate the lensed image generation from the geodesic blueprint."""
    script_dir = os.path.dirname(os.path.abspath(__file__))

    # The default output path is strictly local.
    default_output_path = os.path.join(script_dir, "lensed_output.png")

    # The argument parser manages the visualization configuration and physical bounds.
    parser = argparse.ArgumentParser(
        description="Generate a lensed image from tiled geodesic light blueprints."
    )

    # The output argument defaults to the local file.
    parser.add_argument(
        "--output",
        type=str,
        default=default_output_path,
        help="Path where the output PNG will be saved.",
    )

    parser.add_argument(
        "--window_tiles_width",
        type=int,
        default=1,
        help="Number of horizontal tiles generated by the integrator.",
    )
    
    parser.add_argument(
        "--window_tiles_height",
        type=int,
        default=1,
        help="Number of vertical tiles generated by the integrator.",
    )

    # Physical parameters govern the source accretion disk geometry and the camera window bounds.
    parser.add_argument(
        "--source_r_min",
        type=float,
        default=6.0,
        help="Inner physical radius r_min of the source disk.",
    )
    parser.add_argument(
        "--source_r_max",
        type=float,
        default=20.0,
        help="Outer physical radius r_max of the source disk.",
    )
    parser.add_argument(
        "--window_width",
        type=float,
        default=1.0,
        help="Camera window width w in coordinate units.",
    )
    parser.add_argument(
        "--window_height",
        type=float,
        default=1.0,
        help="Camera window height h in coordinate units.",
    )
    parser.add_argument(
        "--pixel_width",
        type=int,
        default=750,
        help="Pixel width of the final static output image.",
    )

    # The parsed arguments struct contains all runtime configurations.
    args = parser.parse_args()

    # The absolute script directory ensures relative paths resolve independently of the execution context.
    script_dir = os.path.dirname(os.path.abspath(__file__))

    # The list generation deterministically builds the expected file paths based on tile dimensions.
    blueprint_zips = []
    for i in range(args.window_tiles_width):
        for j in range(args.window_tiles_height):
            zip_filename = f"light_blueprint_{i:02d}_{j:02d}.zip"
            zip_filepath = os.path.join(script_dir, zip_filename)
            
            # The existence check prevents reading from missing or uncompiled blueprint payloads.
            if not os.path.exists(zip_filepath):
                print(f"WARNING: Expected tile missing at '{zip_filepath}'.")
            else:
                blueprint_zips.append(zip_filepath)

    if not blueprint_zips:
        print("ERROR: No blueprint zip files found to process.")
        return

    print(f"Loading {len(blueprint_zips)} blueprint tiles...")

    # The texture path locates the high-resolution background celestial sphere image.
    starmap_path = os.path.join(script_dir, cfg.SPHERE_TEXTURE_FILE)

    # The existence check ensures the celestial texture asset is available for projection mapping.
    if not os.path.exists(starmap_path):
        print(f"ERROR: Sphere texture not found at '{starmap_path}'.")
        return

    # The maximum dimension bounds the geometric camera projection window.
    actual_window_width = max(args.window_width, args.window_height)

    # The physical span encompasses the full mathematical diameter of the accretion disk geometry.
    source_physical_width = 2.0 * args.source_r_max

    print("Generating source disk array...")

    # The texture array represents the generated equatorial source disk using the defined radii.
    disk_texture = rli.generate_source_disk_array(
        disk_physical_width=source_physical_width,
        disk_inner_radius=args.source_r_min,
        disk_outer_radius=args.source_r_max,
        colormap=cfg.COLORMAP,
    )

    # Cast the uint8 array to float64 to satisfy mypy type constraints
    disk_texture_float = disk_texture.astype(np.float64)

    print(f"Rendering image to: {args.output}...")

    # The static image generator merges the geodesic blueprint with the texture maps to yield the final visualization.
    rli.generate_static_lensed_image(
        output_filename=args.output,
        output_pixel_width=args.pixel_width,
        source_image_width=source_physical_width,
        sphere_image=starmap_path,
        source_image=disk_texture_float,
        blueprint_filenames=blueprint_zips,
        window_width=actual_window_width,
    )

    print("Visualization complete!")


if __name__ == "__main__":
    main()